language: python
python:
  - "2.7"
install:
  - pip install -r requirements-dev.txt --use-mirrors
  - cp flip/local_settings.py.example flip/local_settings.py
script:  ./manage.py test flip
after_success: coveralls
notifications:
  email:
    recipients:
      - purepython@eaudeweb.ro
