from django.conf.urls import patterns, include, url
from flis import views, auth

# Uncomment the next two lines to enable the admin:
# from django.contrib import admin
# admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    url(r'^$', views.Interlinks.as_view(), name='interlinks'),
    url(r'^interlinks/new$',
        auth.edit_is_allowed(views.InterlinkCreate.as_view()),
        name='interlink_new'),
    url(r'^interlinks/(?P<pk>\d+)/edit$',
        auth.edit_is_allowed(views.InterlinkEdit.as_view()),
        name='interlink_edit'),
    url(r'^interlinks/(?P<pk>\d+)/$', views.Interlink.as_view(), name='interlink_view'),
    url(r'^interlinks/(?P<pk>\d+)/delete$',
        auth.edit_is_allowed(views.InterlinkDelete.as_view()),
        name='interlink_delete'),

    url(r'^sources$', views.Sources.as_view(), name='sources'),
    url(r'^sources/new$',
        auth.edit_is_allowed(views.SourceCreate.as_view()),
        name='source_new'),
    url(r'^sources/(?P<pk>\d+)/edit$',
        auth.edit_is_allowed(views.SourceEdit.as_view()),
        name='source_edit'),
    url(r'^sources/(?P<pk>\d+)/$', views.Source.as_view(), name='source_view'),
    url(r'^sources/(?P<pk>\d+)/delete$',
        auth.edit_is_allowed(views.SourceDelete.as_view()),
        name='source_delete'),

    url(r'^indicators$', views.Indicators.as_view(), name='indicators'),
    url(r'^indicators/new$',
        auth.edit_is_allowed(views.IndicatorCreate.as_view()),
        name='indicator_new'),
    url(r'^indicators/(?P<pk>\d+)/edit$',
        auth.edit_is_allowed(views.IndicatorEdit.as_view()),
        name='indicator_edit'),
    url(r'^indicators/(?P<pk>\d+)/$', views.Indicator.as_view(), name='indicator_view'),
    url(r'^indicators/(?P<pk>\d+)/delete$',
        auth.edit_is_allowed(views.IndicatorDelete.as_view()),
        name='indicator_delete'),

    url(r'^gmts$', views.GMTs.as_view(), name='gmts'),
    url(r'^gmts/new$',
        auth.edit_is_allowed(views.GMTCreate.as_view()),
        name='gmt_new'),
    url(r'^gmts/(?P<pk>\d+)/edit$',
        auth.edit_is_allowed(views.GMTEdit.as_view()),
        name='gmt_edit'),
    url(r'^gmts/(?P<pk>\d+)/$', views.GMT.as_view(), name='gmt_view'),
    url(r'^gmts/(?P<pk>\d+)/delete$',
        auth.edit_is_allowed(views.GMTDelete.as_view()),
        name='gmt_delete'),

    url(r'^trends$', views.Trends.as_view(), name='trends'),
    url(r'^trends/new$',
        auth.edit_is_allowed(views.TrendCreate.as_view()),
        name='trend_new'),
    url(r'^trends/(?P<pk>\d+)/edit$',
        auth.edit_is_allowed(views.TrendEdit.as_view()),
        name='trend_edit'),
    url(r'^trends/(?P<pk>\d+)/$', views.Trend.as_view(), name='trend_view'),
    url(r'^trends/(?P<pk>\d+)/delete$',
        auth.edit_is_allowed(views.TrendDelete.as_view()),
        name='trend_delete'),

    url(r'^settings/thematic_categories$', views.ThematicCategories.as_view(), name='thematic_categories'),
    url(r'^settings/thematic_categories/new$',
        auth.edit_is_allowed(views.ThematicCategoryCreate.as_view()),
        name='thematic_category_new'),
    url(r'^settings/thematic_categories/(?P<pk>\d+)/edit$',
        auth.edit_is_allowed(views.ThematicCategoryEdit.as_view()),
        name='thematic_category_edit'),
    url(r'^settings/thematic_categories/(?P<pk>\d+)/$', views.ThematicCategory.as_view(), name='thematic_category_view'),
    url(r'^settings/thematic_categories/(?P<pk>\d+)/delete$',
        auth.edit_is_allowed(views.ThematicCategoryDelete.as_view()),
        name='thematic_category_delete'),

    url(r'^settings/geographical_scales$', views.GeographicalScales.as_view(), name='geographical_scales'),
    url(r'^settings/geographical_scales/new$',
        auth.edit_is_allowed(views.GeographicalScaleCreate.as_view()),
        name='geographical_scale_new'),
    url(r'^settings/geographical_scales/(?P<pk>\d+)/edit$',
        auth.edit_is_allowed(views.GeographicalScaleEdit.as_view()),
        name='geographical_scale_edit'),
    url(r'^settings/geographical_scales/(?P<pk>\d+)/$', views.GeographicalScale.as_view(), name='geographical_scale_view'),
    url(r'^settings/geographical_scales/(?P<pk>\d+)/delete$',
        auth.edit_is_allowed(views.GeographicalScaleDelete.as_view()),
        name='geographical_scale_delete'),

    url(r'^settings/geographical_coverages$', views.GeographicalCoverages.as_view(), name='geographical_coverages'),
    url(r'^settings/geographical_coverages/new$',
        auth.edit_is_allowed(views.GeographicalCoverageCreate.as_view()),
        name='geographical_coverage_new'),
    url(r'^settings/geographical_coverages/(?P<pk>\d+)/edit$',
        auth.edit_is_allowed(views.GeographicalCoverageEdit.as_view()),
        name='geographical_coverage_edit'),
    url(r'^settings/geographical_coverages/(?P<pk>\d+)/$', views.GeographicalCoverage.as_view(), name='geographical_coverage_view'),
    url(r'^settings/geographical_coverages/(?P<pk>\d+)/delete$',
        auth.edit_is_allowed(views.GeographicalCoverageDelete.as_view()),
        name='geographical_coverage_delete'),

    url(r'^settings/steep_categories$', views.SteepCategories.as_view(), name='steep_categories'),
    url(r'^settings/steep_categories/new$',
        auth.edit_is_allowed(views.SteepCategoryCreate.as_view()),
        name='steep_category_new'),
    url(r'^settings/steep_categories/(?P<pk>\d+)/edit$',
        auth.edit_is_allowed(views.SteepCategoryEdit.as_view()),
        name='steep_category_edit'),
    url(r'^settings/steep_categories/(?P<pk>\d+)/$', views.SteepCategory.as_view(), name='steep_category_view'),
    url(r'^settings/steep_categories/(?P<pk>\d+)/delete$',
        auth.edit_is_allowed(views.SteepCategoryDelete.as_view()),
        name='steep_category_delete'),

    url(r'^settings/timelines$', views.Timelines.as_view(), name='timelines'),
    url(r'^settings/timelines/new$',
        auth.edit_is_allowed(views.TimelineCreate.as_view()),
        name='timeline_new'),
    url(r'^settings/timelines/(?P<pk>\d+)/edit$',
        auth.edit_is_allowed(views.TimelineEdit.as_view()),
        name='timeline_edit'),
    url(r'^settings/timelines/(?P<pk>\d+)/$', views.Timeline.as_view(), name='timeline_view'),
    url(r'^settings/timelines/(?P<pk>\d+)/delete$',
        auth.edit_is_allowed(views.TimelineDelete.as_view()),
        name='timeline_delete'),

    # Uncomment the next line to enable the admin:
    # url(r'^admin/', include(admin.site.urls)),
)
